import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Vendor Management",
  description: "Generated by create next app",
  icons:{icon:"https://cdn-icons-png.flaticon.com/128/17782/17782689.png"}
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  bg-gradient-to-br from-[#0D4C5C] to-[#F76B8A] `}
      >
        {children}
      </body>
    </html>
  );
}
